Update email alerting provider to supply a username
TwiN/gatus pull request #231
Opened 2022-01-06 17:15 UTC by tmoitie

This is intended to maintain backwards compatibility with using Provider.from.

I am unfamiliar with golang so apologies for any style mistakes

2022-01-07 01:16 UTC, TwiN commented
Just so I can understand; this enables using a username that is not the same as the one provided in `alerting.email.from` to authenticate while allowing the usage of `alerting.email.from` as a sender?

2022-01-07 09:36 UTC, tmoitie commented
Yep, that's exactly what I intended

2022-01-07 23:38 UTC, TwiN requested changes
Just a small change, and you're good to go!

2022-01-07 23:38 UTC, TwiN commented on README.md
> +| `alerting.email.username`      | Username of the SMTP server used to send the alert                                         | `alerting.email.from` |
```suggestion
| `alerting.email.username`      | Username of the SMTP server used to send the alert. If empty, uses `alerting.email.from`.  | `""`                  |
```

2022-01-12 01:07 UTC, merged

2022-01-12 01:07 UTC, TwiN commented
@tmoitie Thank you for your contribution!