feat(alert): Add group-specific to email list
TwiN/gatus pull request #264
Opened 2022-03-19 07:17 UTC by appleboy

Add group-specific to list for email alert

Provides support for paging multiple teams based on the group selector while keeping backward compatibility to the old email configuration manifest

integration per team can be specified in the overrides sections in an array form.

```yaml
alerting:
  email:
    from: "from@example.com"
    username: "from@example.com"
    password: "hunter2"
    host: "mail.example.com"
    port: 587
    to: "recipient1@example.com,recipient2@example.com"
    overrides:
      - group: "core"
        to: "recipient3@example.com,recipient4@example.com"
```

ref: https://github.com/TwiN/gatus/issues/96

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

2022-03-20 21:10 UTC, TwiN requested changes

2022-03-21 01:28 UTC, appleboy commented on README.md
> +| `alerting.email.overrides[].to` | Email(s) to send the alerts to                                                    | `""`    |
Done. [`bf77fb4` (#264)](https://github.com/TwiN/gatus/pull/264/commits/bf77fb4c171fba9073192c06dfb11fe908ad13bd)

2022-03-21 01:51 UTC, TwiN commented on README.md
> +| `alerting.email.overrides[].to` | Email(s) to send the alerts to                                                    | `""`    |
Perfect, thanks!

2022-03-21 01:53 UTC, TwiN approved these changes
Thank you for your contribution!

2022-03-21 01:54 UTC, merged

2022-03-23 03:14 UTC, TwiN commented
Released in [v3.7.0](https://github.com/TwiN/gatus/releases/tag/v3.7.0)