Send alerts to multiple Slack channels
TwiN/gatus pull request #279
Opened 2022-04-28 12:48 UTC by mani9223-oss

2022-04-28 13:31 UTC, mani9223-oss commented
@TwiN Please check. Fixed indent issues

2022-04-28 21:58 UTC, TwiN requested changes

2022-04-28 21:58 UTC, TwiN commented on README.md
> +| `alerting.slack.overrides[].webhook-url` | Slack Webhook URL                                                                        | `""`          |
Could you please fix the table format so that all columns are of the same size? 🙏

2022-04-28 21:58 UTC, TwiN commented on alerting/provider/slack/slack.go
>  	"github.com/TwiN/gatus/v3/alerting/alert"
Could you undo this change?

2022-04-28 21:58 UTC, TwiN commented on alerting/provider/slack/slack_test.go
> +func TestAlertProvider_IsValidWithOverride(t *testing.T) {
Could you re-add a newline between these two?

2022-04-29 05:02 UTC, mani9223-oss commented
@TwiN Changes are done

2022-04-29 23:01 UTC, TwiN requested changes
It appears like the Go code you've added is double indented; could you fix it please? 🙏

2022-05-04 08:20 UTC, appleboy commented on alerting/provider/slack/slack.go
> -
redundant tab

2022-05-07 18:38 UTC, TwiN approved these changes

2022-05-07 18:45 UTC, TwiN requested changes

2022-05-07 18:45 UTC, TwiN commented on alerting/provider/slack/slack_test.go
> -		Endpoint     core.Endpoint
Why did you remove this? 🤔 Some tests seem to be failing because of this

2022-05-17 05:36 UTC, Coolomina commented
👋🏻  Why are we choosing this specific implementation when we can have channel override instead of webhook_url override?

That way we could have several groups benefitting from the same webhook_url. Easier to maintain, easier to rotate. What do you think ?

2022-05-18 04:03 UTC, TwiN commented
> 👋🏻 Why are we choosing this specific implementation when we can have channel override instead of webhook_url override?
> 
> That way we could have several groups benefitting from the same webhook_url. Easier to maintain, easier to rotate. What do you think ?, I guess it would be a matter of modifying the request body https://github.com/TwiN/gatus/blob/master/alerting/provider/slack/slack.go#L70
> 
> (edit): There are organisations that rely on Security team to configure these kinds of configuration, as this can easily be treated as a secret, so if you were to have 200 apps, having 200 slack webhooks sounds terrible.

Hello @Coolomina, last I checked, channel overrides do not work on Slack; this is why we don't use channel overrides. 

Well, Slack's legacy "Incoming webhooks" app does still support it, but I'm not sure I want to build features around "deprecated" features, as that would lead to confusion.

[source](https://api.slack.com/legacy/custom-integrations/messaging/webhooks)

If you look at the non-legacy counterpart [here](https://api.slack.com/messaging/webhooks), they make no mention of channel overrides.

2022-05-26 08:29 UTC, Coolomina commented
Thanks for the answer @TwiN :)

I totally agree with you in not building features for legacy integrations, I just did not know this was on its way to deprecation. 

I still think it does not scale as it's very easy for an org to have +5 delivery teams with their own alerting channels. I'll contact Slack support and see what the best practice is here.

Thank you again!

2022-05-30 08:53 UTC, Coolomina commented
@TwiN @mani9223-oss need any help with the PR?. Happy to help.

2022-05-31 02:02 UTC, TwiN approved these changes

2022-05-31 02:03 UTC, merged

2022-05-31 02:04 UTC, TwiN commented
Thank you for the contribution @mani9223-oss!

2022-06-21 01:52 UTC, TwiN commented
Released in [v4.0.0](https://github.com/TwiN/gatus/releases/tag/v4.0.0)