Feature/mattermost overrides
TwiN/gatus pull request #292
Opened 2022-06-13 19:12 UTC by mindcrime-ilab

## Summary
This PR adds the the override option for the Mattermost alert integration.

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable. 
- [X] Added the documentation in `README.md`, if applicable.

2022-06-13 23:09 UTC, TwiN requested changes

2022-06-13 23:09 UTC, TwiN commented on alerting/provider/mattermost/mattermost.go
> +
```suggestion
	if provider.Overrides != nil {
		registeredGroups := make(map[string]bool)
		for _, override := range provider.Overrides {
			if isAlreadyRegistered := registeredGroups[override.Group]; isAlreadyRegistered || override.Group == "" || len(override.WebhookURL) == 0 {
				return false
			}
			registeredGroups[override.Group] = true
		}
	}
```

2022-06-16 00:30 UTC, TwiN approved these changes
Looks great!

2022-06-16 03:25 UTC, merged

2022-06-16 04:59 UTC, mindcrime-ilab commented
Thanks for the merge and for your kind support.