Feat: put InjectHTTPClient on Config
TwiN/gatus pull request #469
Opened 2023-05-06 18:41 UTC by Mehrbod2002

Fixes : #398 
Move method to client.Config

2023-05-19 22:00 UTC, TwiN commented on core/endpoint_test.go
> +	config := client.GetDefaultConfig()
Same as above

2023-05-19 22:05 UTC, Mehrbod2002 commented
@TwiN what is that failure for ?

2023-05-19 22:16 UTC, TwiN commented
I think you may have forgotten to update the alerting providers themselves - you only updated their tests.

2023-05-21 16:20 UTC, TwiN requested changes
You haven't addressed my last comment - you've mostly made changes in the test, but you haven't modified how the client configuration is used outside of the tests.

For instance, the discord provider is passing a nil client configuration in https://github.com/Mehrbod2002/gatus/blob/7d3b7711c838aebb8ddb226aed0f7c6f0c4bc592/alerting/provider/discord/discord.go#L54

2023-05-21 19:54 UTC, Mehrbod2002 commented
@TwiN Sorry I got confused .
Did you mean this ? 
Please guide me if it's incorrect as I am a new developer :) Thanks

2023-12-17 16:14 UTC, closed without merging