Feat/modify discord title
TwiN/gatus pull request #602
Opened 2023-10-30 17:39 UTC by bugrakocabay

Hello @TwiN ,

## Summary
Regarding #508, I believe it will be useful to allow users configure the title, making them more free. Maybe the same configuration can be made on other providers as well.

## Checklist
- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [x] Updated documentation in `README.md`, if applicable.

2023-10-31 03:17 UTC, TwiN requested changes
Please add some tests

2023-10-31 05:09 UTC, bugrakocabay commented
Done. @TwiN

2023-11-01 00:01 UTC, TwiN approved these changes

2023-11-01 00:01 UTC, merged

2023-11-01 00:02 UTC, TwiN commented
@bugrakocabay Thank you for the contribution!