feat(alerting): add alerting support for jetbrains space
TwiN/gatus pull request #713
Opened 2024-03-22 18:23 UTC by michael-baraboo

## Summary

Adds [JetBrains Space](https://www.jetbrains.com/space/) chat channels as an alerting option.

Pretty directly translated from the Slack provider, if there's a better example to follow for new alerting providers let me know.

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

2024-03-23 14:35 UTC, TwiN requested changes
Great work!

I think the only thing you missed is updating this: https://github.com/TwiN/gatus/blob/5aa83ee274e92f37a771d0e9cb797ef36f13e176/alerting/provider/provider.go#L60

2024-03-28 22:32 UTC, khinshankhan approved these changes

2024-03-28 22:32 UTC, khinshankhan approved these changes

2024-03-28 22:36 UTC, TwiN approved these changes
@michael-baraboo Looks good! Thank you for your contribution :) 

and thank you @khinshankhan for double checking for me ❤️

2024-03-28 22:36 UTC, merged