Teams Custom Title
TwiN/gatus pull request #731
Opened 2024-04-12 14:30 UTC by rahulchordiya

## Summary

## Checklist

- [ ] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [ ] Updated documentation in `README.md`, if applicable.

2024-04-12 14:30 UTC, rahulchordiya reviewed
Approve

2024-04-19 00:45 UTC, TwiN requested changes
Can you add a test and document the new feature in the README?

2024-04-19 09:05 UTC, rahulchordiya commented
README udpated.

2024-05-04 23:23 UTC, TwiN approved these changes

2024-05-04 23:24 UTC, merged