Teams Workflow Alert (Issue #820)
TwiN/gatus pull request #847
Opened 2024-08-27 12:59 UTC by JamesHillyard

## Summary
Resolves issue #820 by introducing a new `teamsworkflow` alert compatible with Teams Workflows. Microsoft is deprecating the O365 webhook connector for Teams Workflows with MS Power Automate ([Source: Microsoft DevBlog](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/)).

The new Workflows require [Microsoft Adaptive Cards](https://adaptivecards.io/) and have a proprietary JSON format that means the old `teams` connector using a new Workflow URL will fail with this error:
```
The execution of template action 'Send_each_adaptive_card' failed: the result of the evaluation of 'foreach' expression '@triggerOutputs()?['body']?['attachments']' is of type 'Null'. The result must be a valid array.
```

## Breaking Changes
**There are no breaking changes**. The old `teams` alert still exists and will work with legacy O365 Webhook URLs.

There are no breaking changes in configuring the `teams` and `teamswebhook` alerts, meaning migration is simple.

## Migrating to new Teams Webhooks
End-users will need to make the following changes to migrate from the legacy `teams` alerts to `teamswebhook` alerts:
- Create a Workflow in Microsoft Teams for incoming webhooks. [Microsoft Documentation](https://support.microsoft.com/en-us/office/create-incoming-webhooks-with-workflows-for-microsoft-teams-8ae491c7-0394-4861-ba59-055e33f75498)
- Replace all occurences of `teams` (In `alerting` and `endpoints[].alerts`) with `teamsworkflow`
- Replace the `alerting.teams.webhook-url` (Now `alerting.teamsworkflow.webhook-url`) with the new URL generated in the Teams Workflow

## Configuring the `teamsworkflow` Alert
### MS Teams Configuration
![image](https://github.com/user-attachments/assets/1c6005b8-1553-4491-916d-a1e4d935153f)

### Gatus Configuration
```yml
alerting:
  teamsworkflow:
    webhook-url: "[WORKFLOW-WEBHOOK-URL-HERE]"
    default-alert:
      description: ""
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

endpoints:
  # Website Group
  - name: front-end
    url: https://www.google.com
    interval: 3s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 50"
    alerts:
      - type: teamsworkflow
        description: "Description Lies Here"
```

## Remaining Issues
There are a few remaining issues, none are blockers to using this feature, but likely should be addressed in the future with further investigation.

### Adaptive Card Version >1.5
Using an Adaptive Card higher than 1.4 (1.6 is latest) results in the message showing 
> We're sorry, this card couldn't be displayed

This has been reported to AdaptiveCards ([Report](https://www.github.com/microsoft/AdaptiveCards/issues/7676)), but discussion around this issue seems very low.

### Card Width
The cards do not show on teams as full-width. A [StackOverflow post](https://stackoverflow.com/questions/59728112/increase-the-width-of-adaptive-card-for-ms-teams-channel) would suggest the width can be changed, but I wasn't able to get this to work.

### Card Colour Strip
The red and green colour strip on the old teams cards at the top for triggered/resolved is not supported in Adaptive Cards. There are workaround options as identified in this [Stack Overflow post](https://stackoverflow.com/questions/72873499/adding-a-colored-strip-on-the-top-of-adaptive-card) but it doesn't look great.

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

2024-09-04 02:48 UTC, TwiN requested changes
Great work! The only real change I see here is renaming teamsworkflow` to `teams-workflows`.

Not a super big deal, but looking at https://support.microsoft.com/en-us/office/creating-a-workflow-from-a-channel-in-teams-242eb8f2-f328-45be-b81f-9817b51a5f0e, it seems like their service is "Workflows", not "Workflow", and well, I'd rather avoid confusion.

In a later version of Gatus, I'll probably get rid of the current `teams` once they get rid of the O365 connectors and replace it for this implementation.

2024-09-04 02:48 UTC, TwiN commented on alerting/config.go
> +	TeamsWorkflow *teamsworkflow.AlertProvider `yaml:"teamsworkflow,omitempty"`
```suggestion
	TeamsWorkflow *teamsworkflow.AlertProvider `yaml:"teams-workflow,omitempty"`
```

2024-09-04 02:48 UTC, TwiN commented on README.md
> +| `alerting.teamsworkflow`  | Configuration for alerts of type `teamsworkflow`. <br />See [Configuring Teams Workflow alerts](#configuring-teams-workflow-alerts).     | `{}`    |
```suggestion
| `alerting.teamsworkflow`  | Configuration for alerts of type `teamsworkflow`. <br />See [Configuring Teams Workflow alerts](#configuring-teams-workflow-alerts).     | `{}`    |
```
could you rename `teamsworkflow` to `teams-workflows` here?

2024-09-04 02:48 UTC, TwiN commented on README.md
> +| `alerting.teamsworkflow.overrides[].webhook-url` | Teams WorkFlow Webhook URL                                                                 | `""`               |
Same here

2024-09-04 02:48 UTC, TwiN commented on README.md
> +    - [Configuring Teams Workflow alerts](#configuring-teams-workflow-alerts)
```suggestion
    - [Configuring Teams Workflows alerts](#configuring-teams-workflows-alerts)
```

2024-09-04 02:48 UTC, TwiN commented on README.md
> +        send-on-resolved: true
```suggestion
alerting:
  teams-workflows:
    webhook-url: "https://********.webhook.office.com/webhookb2/************"
    # You can also add group-specific to keys, which will
    # override the to key above for the specified groups
    overrides:
      - group: "core"
        webhook-url: "https://********.webhook.office.com/webhookb3/************"

endpoints:
  - name: website
    url: "https://twin.sh/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: teams-workflows
        description: "healthcheck failed"
        send-on-resolved: true
```

2024-09-04 02:48 UTC, TwiN commented on alerting/provider/teamsworkflow/teamsworkflow.go
> +package teamsworkflow
```suggestion
package teamsworkflows
```
the path should also be changed.

2024-09-04 08:57 UTC, JamesHillyard commented
@TwiN Makes sense, I have renamed `teamsworkflows` to `teams-workflows` and tested it still works. Thanks for the review!

2024-09-12 01:26 UTC, TwiN approved these changes

2024-09-12 01:31 UTC, TwiN commented
@JamesHillyard Looks like some of your tests are failing

```
 --- FAIL: TestAlertProvider_buildRequestBody (0.00s)
    --- FAIL: TestAlertProvider_buildRequestBody/triggered (0.00s)
        teamsworkflows_test.go:189: expected:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x1f6a8 Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been triggered due to having failed 3 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x274C;","value":"[CONNECTED] == true"},{"title":"\u0026#x274C;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
            got:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x26D1; Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been triggered due to having failed 3 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x274C;","value":"[CONNECTED] == true"},{"title":"\u0026#x274C;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
    --- FAIL: TestAlertProvider_buildRequestBody/resolved (0.00s)
        teamsworkflows_test.go:189: expected:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x1f6a8 Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x2705;","value":"[CONNECTED] == true"},{"title":"\u0026#x2705;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
            got:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x26D1; Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x2705;","value":"[CONNECTED] == true"},{"title":"\u0026#x2705;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
    --- FAIL: TestAlertProvider_buildRequestBody/resolved-with-no-conditions (0.00s)
        teamsworkflows_test.go:189: expected:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x1f6a8 Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
            got:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x26D1; Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
FAIL
coverage: 93.5% of statements
FAIL	github.com/TwiN/gatus/v5/alerting/provider/teamsworkflows	0.026s
```

2024-09-12 01:31 UTC, TwiN requested changes
@JamesHillyard Looks like some of your tests are failing

```
 --- FAIL: TestAlertProvider_buildRequestBody (0.00s)
    --- FAIL: TestAlertProvider_buildRequestBody/triggered (0.00s)
        teamsworkflows_test.go:189: expected:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x1f6a8 Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been triggered due to having failed 3 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x274C;","value":"[CONNECTED] == true"},{"title":"\u0026#x274C;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
            got:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x26D1; Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been triggered due to having failed 3 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x274C;","value":"[CONNECTED] == true"},{"title":"\u0026#x274C;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
    --- FAIL: TestAlertProvider_buildRequestBody/resolved (0.00s)
        teamsworkflows_test.go:189: expected:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x1f6a8 Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x2705;","value":"[CONNECTED] == true"},{"title":"\u0026#x2705;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
            got:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x26D1; Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false,"facts":[{"title":"\u0026#x2705;","value":"[CONNECTED] == true"},{"title":"\u0026#x2705;","value":"[STATUS] == 200"}]}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
    --- FAIL: TestAlertProvider_buildRequestBody/resolved-with-no-conditions (0.00s)
        teamsworkflows_test.go:189: expected:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x1f6a8 Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
            got:
            {"attachments":[{"content":{"type":"AdaptiveCard","version":"1.4","body":[{"type":"TextBlock","text":"\u0026#x26D1; Gatus","wrap":false,"size":"Medium","weight":"Bolder"},{"type":"TextBlock","text":"An alert for **endpoint-name** has been resolved after passing successfully 5 time(s) in a row.","wrap":true},{"type":"FactSet","wrap":false}]},"contentType":"application/vnd.microsoft.card.adaptive"}],"type":"message"}
FAIL
coverage: 93.5% of statements
FAIL	github.com/TwiN/gatus/v5/alerting/provider/teamsworkflows	0.026s
```

2024-10-09 11:13 UTC, JamesHillyard commented
@TwiN Looks like the text was expecting a broken teams emoji.. I must have changed it last minute and not updated the test. I've now fixed it and running `go test -v .\alerting\provider\teamsworkflows\` results in all tests passing.

2024-10-15 11:04 UTC, deebify commented
When can I use the new teams-workflows workflow?

2024-10-15 21:24 UTC, TwiN approved these changes

2024-10-15 21:25 UTC, merged

2024-10-15 21:25 UTC, TwiN commented
@JamesHillyard Great work & thank you for the contribution!

2024-10-25 03:39 UTC, TwiN commented
@liamjones-pw I usually let new features soak in latest for some time to give people time to report issues. If people are already using the feature and haven't reported any issues, I can create a release for it this weekend 👀

2024-10-26 01:41 UTC, TwiN commented
@liamjones-pw I just released v5.13.0