introduces TwiN/logr library
TwiN/gatus pull request #872
Opened 2024-09-30 20:49 UTC by garyhodgson

## Summary

Introduces logr library as per https://github.com/TwiN/gatus/discussions/871

I'm not a Go Developer, so apologies if the attempt isn't very go-ish.

I couldn't see a way to use enums for mapping the log level names to logr.Level ints, so I made use of this library: https://hermannm.dev/enumnames

I performed a few manual tests, not sure how unit tests of log output would work.

## Checklist
- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

2024-09-30 23:11 UTC, TwiN requested changes
Given that you've never written Go before, you're doing excellent work!

2024-09-30 23:11 UTC, TwiN commented on config/config.go
> +	LogLevel string `yaml:"log-level,omitempty"`
I just made a couple changes to the library - you should now be able to just use `logr.Level` as I've made it into a string.

This way, you won't have to worry about converting anything.

2024-09-30 23:11 UTC, TwiN commented on config/config.go
> +	}
```suggestion
	if config.LogLevel == "" {
		config.LogLevel = logr.LevelInfo
	}
```
once you took care of the previous suggestion, you should be able to just use this directly

2024-09-30 23:11 UTC, TwiN commented on main.go
> +}
I also just introduced the `logr.LevelFromString` function, which should help you with this.

The aforementioned function should return an error if the existing value isn't valid

2024-09-30 23:11 UTC, TwiN commented
FYI, don't hesitate to let me know if you want me to add something else to the logr library.

2024-09-30 23:32 UTC, TwiN commented on config/config.go
> +	}
it's fine to have this anyways, but I also just made a change in the library to make it so if an invalid/unsupported threshold is set, it automatically defaults to INFO

2024-10-01 18:26 UTC, garyhodgson commented
Hi. All good suggestions, the changes to logr make it a easier to integrate :+1: 

As far as suggestions, I can imagine convenience methods such as `isDebug()` for `logr.GetThreshold() == logr.LevelDebug` checks would prove useful.

2024-10-23 01:14 UTC, TwiN requested changes

2024-10-23 01:14 UTC, TwiN commented on watchdog/watchdog.go
> +
```suggestion
	logr.Debugf("[watchdog.execute] Monitoring group=%s; endpoint=%s", ep.Group, ep.Name)
```

2024-10-23 01:14 UTC, TwiN commented on main.go
> +
```suggestion
```

2024-10-23 01:14 UTC, TwiN commented on main.go
> +
```suggestion
```

2024-10-23 01:14 UTC, TwiN commented on go.mod
> +toolchain go1.23.0
```suggestion
```

2024-10-23 01:14 UTC, TwiN commented on config/config.go
> +	LogLevel logr.Level `yaml:"log-level,omitempty"`
```suggestion
	// LogLevel is one of DEBUG, INFO, WARN and ERROR. Defaults to INFO
	LogLevel logr.Level `yaml:"log-level,omitempty"`
```

2024-10-23 01:14 UTC, TwiN commented on watchdog/watchdog.go
> +
```suggestion
```

2024-10-30 09:04 UTC, g-hodgson-tup commented
Hi - requested changes have been pushed.

2024-11-04 23:43 UTC, TwiN commented on go.mod
> +go 1.22.4
```suggestion
go 1.22.2
```

2024-11-04 23:43 UTC, TwiN commented on config.yaml
> +log-level: INFO
```suggestion
```

2024-11-04 23:44 UTC, TwiN commented on watchdog/watchdog.go
> +
```suggestion
```

2024-11-04 23:58 UTC, TwiN commented on watchdog/watchdog.go
> +
```suggestion
```

2024-11-14 00:02 UTC, TwiN approved these changes
Thank you for the contribution!

2024-11-14 00:02 UTC, merged

2024-11-14 04:16 UTC, TwiN commented
@garyhodgson FYI I decided to move log-level to an environment variable - see #895