feat(alerting): Added the ability to send messages to Telegram topics…
TwiN/gatus pull request #928
Opened 2024-12-07 12:22 UTC by medaved

## Summary
* Added the ability to send messages to Telegram topics in groups.

## Checklist
- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

2024-12-08 23:33 UTC, TwiN commented
Hey, just so you know, I'm currently working on #929, which _may_ also implement what this PR is implementing.

2024-12-09 10:28 UTC, medaved commented
@TwiN how can i help with this?

2024-12-16 02:15 UTC, TwiN commented
Hey, sorry about this, I'm going to close this because I've been working on adding support for provider overrides at the alert level, and this impacts how overrides in general work. The good news is that you'll be able to override the topic parameter with this change, making this PR no longer necessary. 

I am, however, very thankful for your contribution!

2025-01-06 15:36 UTC, 0n1cOn3 commented
Hey @medaved 

I don't see any connection here. Telegram Topics have nothing to do with the endpoints per se. But rather that support for topics is introduced here. It would make notifications a lot easier to handle and would no longer clutter up the main chat. Please take another look at this PR :)

2025-01-07 01:10 UTC, TwiN commented
@0n1cOn3 oh crap, you're completely right. I went through the files changes way too quickly, saw green and overrides & assumed it was the change 🤦‍♂️

2025-01-07 12:04 UTC, medaved commented
@TwiN PR refreshed, because old commit had conflicts

2025-01-16 04:06 UTC, TwiN commented
@medaved Some tests are failing

```
# github.com/TwiN/gatus/v5/alerting/provider/telegram [github.com/TwiN/gatus/v5/alerting/provider/telegram.test]
Error: alerting/provider/telegram/telegram_test.go:159:32: unknown field ID in struct literal of type AlertProvider
Error: alerting/provider/telegram/telegram_test.go:159:43: unknown field TopicId in struct literal of type AlertProvider
```

2025-01-23 09:42 UTC, medaved commented
@TwiN broken tests were fixed

2025-02-16 19:11 UTC, TwiN requested changes

2025-02-16 19:11 UTC, TwiN commented on alerting/provider/telegram/telegram.go
> +	TopicId   string `json:"message_thread_id,omitempty"`
Should be TopicID

2025-02-17 05:04 UTC, medaved commented on alerting/provider/telegram/telegram.go
> +	TopicId   string `json:"message_thread_id,omitempty"`
fixed

2025-03-18 19:28 UTC, TwiN requested changes

2025-03-18 19:28 UTC, TwiN commented on README.md
> +| `alerting.telegram.topic-id`          | Telegram Topic ID in Group                                                                 | `""`                       |
Can you specify that this also corresponds to `message_thread_id`?

2025-05-29 16:41 UTC, TwiN commented
@sw5ciprl Did you check the review I left at https://github.com/TwiN/gatus/pull/928#discussion_r2001846502? 

Once you've addressed the comment, I'll re-review

2025-05-29 16:41 UTC, TwiN commented
@sw5ciprl I left a comment at https://github.com/TwiN/gatus/pull/928#discussion_r2001846502? 

Once @medaved has addressed the comment, I'll re-review

2025-05-30 08:39 UTC, medaved commented on README.md
> +| `alerting.telegram.topic-id`          | Telegram Topic ID in Group                                                                 | `""`                       |
@TwiN done

2025-06-02 13:57 UTC, sw5ciprl commented
@TwiN Could you please review?

2025-07-11 16:47 UTC, sw5ciprl commented
@TwiN I've been running Gatus with this patch for around a month now, it's stable, no issues. Please merge this.

2025-07-11 17:55 UTC, merged

2025-07-11 17:57 UTC, TwiN commented
@sw5ciprl Thank you, usually I wait until I test the changes myself, but having a 3rd party confirm it works as intended is a great replacement. Appreciate the feedback :)

2025-07-11 17:57 UTC, TwiN commented
@medaved Thank you for the contribution!