replace html entities with emojis to prevent rendering issues
TwiN/gatus pull request #941
Opened 2024-12-20 16:12 UTC by pieceofsoul

## Summary

Emojis written as HTML entities are not working as expected. Especially on mobilde devices (android) the entity is not rendered. Desktop seems to work. The assumption is that there is no full support of html entities for adaptive cards: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cdesktop1%2Cdesktop2%2Cconnector-html

However, replacing them with emojis itself, works on desktop and mobile devices.

## Checklist

- [x] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [x] Updated documentation in `README.md`, if applicable.

Verified by running gatus locally with a local config. Desktop and mobile view are both showing the emojis in an appropriate way.

2024-12-28 16:19 UTC, TwiN submitted a review, later dismissed

2024-12-28 16:24 UTC, TwiN requested changes
You'll have to update the tests as well

2024-12-29 06:48 UTC, pieceofsoul commented
Apologies for the oversight. I've updated the tests, and they are now passing as expected.

2025-01-14 04:14 UTC, TwiN approved these changes

2025-01-14 04:18 UTC, merged